apiVersion: v1
kind: Namespace
metadata:
  name: optional3
  labels:
    training: block3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus3
  namespace: optional3
  labels:
    training: block3
spec:
  replicas: 1
  selector:
    matchLabels:
      training: block3
  template:
    metadata:
      labels:
        training: block3
    spec:
      containers:
      - name: quarkus3
        image: quay.io/drsylent/cubix/block3/optional:quarkus3
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: FILE_LOCATION
          value: "/deployments/optional.txt"
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus3
  namespace: optional3
  labels:
    training: block3
spec:
  type: ClusterIP
  selector:
    training: block3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus3
  namespace: optional3
  labels:
    training: block3
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quarkus3
            port:
              number: 8080
